### ISSUE TITLE
You use deprecated version of AssemblyScript

### ISSUE THREAD

**Issue by MaxGraey** [sleagon/hello-webassembly#1]
plz install latest (0.6.0) via command:
```
npm install --save-dev github:AssemblyScript/assemblyscript
```

Enjoy the use of AssemblyScript project!

**Comment by sleagon** [comment]
The master branch of assemblyscript was broken when i tried. It seems to have been fixed now. Version 0.6.0 is used now. Thanks very much for your timely advice.
